### ISSUE TITLE
Game list doesn't update

### ISSUE THREAD

**Issue by mccorkled** [shawly/docker-ps3netsrv#11]
It's very possible that I have installed this wrong but the following is my Docker compose

version: '3'
services:
  ps3netsrv:
    image: shawly/ps3netsrv
    environment:
      - TZ: America/New_York
      - PUID: 1027
      - GUID: 101
    ports:
      - "38008:38008"
    volumes:
      - Games/Sony Playstation 3/_ISOs: /games:rw"

**Comment by shawly** [comment]
Have you verified that this issue doesn't appear with the standalone version of ps3netsrv?

**Comment by mccorkled** [comment]
I have the stand alone version working fine.

**Comment by shawly** [comment]
Alright, please execute **docker exec \<container name or id\> ls -l /games** and post the output here for me.

**Comment by mccorkled** [comment]
Error: No such container: ls

**Comment by shawly** [comment]
Sorry, git hid the formatting, execute `docker exec CONTAINERNAME ls -l /games` replace CONTAINERNAME with your containers name or id

**Comment by mccorkled** [comment]
-rwx------ 1 1024 users  3118813184 Nov 30 16:52 Plants vs. Zombies - Garden War                                      fare (USA).iso

**Comment by shawly** [comment]
Your folder permissions aren't correct, the files should be owned by the PUID and GUID you used in your docker-compose file or you need to change your compose file to use the permissions of your games. Since you used PUID 1027 and your Plants vs Zombies.iso is owned by user 1024 and is configured to be read only by it's owner, ps3netsrv can't see it.

Also you directly mounted your ISO folder, which from my knowledge does not work, your folder structure needs to look like this:

```docker exec ps3netsrv_ps3netsrv_1 ls -l /games
drwxrwx--- 119 ps3netsrv ps3netsrv 119 Mar  4  2019 GAMES
drwxrwx---   2 ps3netsrv ps3netsrv 215 Mar 17  2019 PS2ISO
drwxrwx---   7 ps3netsrv ps3netsrv   7 Jun 21  2019 PS3ISO
drwxrwx---   2 ps3netsrv ps3netsrv 420 Oct  5  2019 PSXISO
```

Whereas your .isos have to be put into the PS3ISO folder.

**Comment by mccorkled** [comment]
I’m new to Linux and finding out most of my problems stem from permission issues. 

As for the folder structure... on the stand alone I used GAMES/PS3ISO/game name.iso and WebMan couldn’t find it until it until I moved the ISO into /GAMES.

**Comment by mccorkled** [comment]
So I looked at my permissions and the admin 1027 has rw permissions for that folder. I am also running the Docker as admin so I am unsure where the error lies.

**Comment by mccorkled** [comment]
Okay, so I didn't realize that I was using my home automation user and changed it to 1024 (admin). It still wasn't working so I tried to move the games around a bit. I tried to move them to /GAMES and /GAMES/PS3ISO as well as change the container mapping from Games/Playstation 3/_ISOS to Games/Playstation 3/_ISOS/GAMES. It still won't show any of the ISOs.

-rwx------ 1 1024 users  4392263680 Nov 30 18:55 Rayman Origins (USA).iso

**Comment by shawly** [comment]
Your permissions are still wrong, because you set the wrong variables for the user and group id, look at the README here https://github.com/shawly/docker-ps3netsrv#docker-compose-file

I added a troubleshooting section to the README https://github.com/shawly/docker-ps3netsrv#troubleshooting

**Comment by shawly** [comment]
If you still have issues after following all the troubleshooting steps, please create a new issue with the Help request template: https://github.com/shawly/docker-ps3netsrv/issues/new?assignees=shawly&labels=help+wanted&template=help-request.md&title=%5BHELP%5D%20Your%20title

Make sure to execute all commands that were suggested there.

**Comment by mccorkled** [comment]
Just wanted to say thank you for your help. I have this working.
