### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by DafreyG** [shawly/docker-ps3netsrv#13]
**I have read and followed [all troubleshooting steps from the README.md](https://github.com/shawly/docker-ps3netsrv#troubleshooting)?**

```
SSBoYXZlIHJlYWQsIGZvbGxvd2VkIGFuZCB0cmllZCBldmVyeSB0cm91Ymxlc2hvb3Rpbmcgc3RlcCwgYnV0IGl0IHN0aWxsIGRvZXNuJ3Qgd29yaywgcGxlYXNlIGhlbHAgbWUu
```

**System configuration:**  
Hi Shawly,
First, I am really grateful for your work.
I just want to run ps3netsrv on a brand new Synology NAS DS920+.
But I tried unsuccessfully both methods (docker and docker-compose).
It looks like I can't override correctly gid permissions :|

Notes:
It is working fine on Windows and Linux but I want it to run on my NAS to be as close as possible to PS3 games files and avoid useless network round trip traffic between PS3, storage and ps3netsrv.

Wishing you happy new year.

Output of `docker version`:
```
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        bfed4f5
 Built:             Fri Mar 13 06:46:11 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.8
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11
  Git commit:       3a371f3
  Built:            Fri Mar 13 06:44:35 2020
  OS/Arch:          linux/amd64
  Experimental:     false
```

Output of `docker ps -a -f "ancestor=shawly/ps3netsrv"`:
```
docker ps -a -f "ancestor=shawly/ps3netsrv"
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS                     PORTS                      NAMES
51ec97689d9a        shawly/ps3netsrv:latest   "/init"             13 hours ago        Up 4 minutes               0.0.0.0:38008->38008/tcp   ps3netsrv
```

Output of `docker logs CONTAINERNAME` (replace *CONTAINERNAME* with your ps3netsrv container's name):
```
-------------------------------------
GID/UID
-------------------------------------

User uid:    1024
User gid:    100
-------------------------------------

[cont-init.d] 00-adduser: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-adduser: executing...
usermod: no changes

-------------------------------------
GID/UID
-------------------------------------

User uid:    1024
User gid:    100
-------------------------------------

[cont-init.d] 00-adduser: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

Output of `id` (you should be logged in with the user that owns your games directory):
```
uid=1024(admin) gid=100(users) groups=100(users),101(administrators)
```

Output of `docker exec --user ps3netsrv CONTAINERNAME id` (replace *CONTAINERNAME* with your ps3netsrv container's name):
```
uid=1024(ps3netsrv) gid=100(users) groups=100(users)
```

Output of `ls -l /path/to/your/games/folder`:
```
total 4
d---------+ 1 admin users   46 Nov 30 19:26 .
d---------+ 1 admin users   16 Jul  2 00:25 ..
d---------+ 1 admin users 4040 Dec  1 23:40 GAMES
d---------+ 1 admin users  224 Dec  1 23:05 PKG
d---------+ 1 admin users  232 Nov 30 19:36 PS3ISO
```

Output of `docker exec CONTAINERNAME ls -l /games` (replace *CONTAINERNAME* with your ps3netsrv container's name):
```
total 4
d--------- 1 ps3netsrv users 4040 Dec  1 22:40 GAMES
d--------- 1 ps3netsrv users  224 Dec  1 22:05 PKG
d--------- 1 ps3netsrv users  232 Nov 30 18:36 PS3ISO
```

My docker run command or my docker-compose.yml:
```
version: '3'
services:
  ps3netsrv:
    image: shawly/ps3netsrv
    network_mode: bridge
    environment:
      - "TZ=Europe/Paris"
      - "USER_ID=1024"
      - "GROUP_ID=1000"
    ports:
      - "38008:38008"
    volumes:
      - "/volume1/DATA/COMMUN/JEUX/PS3:/games:rw"
```

**Comment by shawly** [comment]
Quite strange that your GROUP_ID env var is set to 1000 but the ps3netsrv user within the container still has the gid 100.
Tough the ownership of your folders is still right, the problem are the permissions on your folders.

```
total 4
d---------+ 1 admin users   46 Nov 30 19:26 .
d---------+ 1 admin users   16 Jul  2 00:25 ..
d---------+ 1 admin users 4040 Dec  1 23:40 GAMES
d---------+ 1 admin users  224 Dec  1 23:05 PKG
d---------+ 1 admin users  232 Nov 30 19:36 PS3ISO
```

It seems that your folders do not even have read/write permissions for the owner, which would explain why ps3netsrv can't read your games. (`d---------+ 1 admin users`)

It should rather look similar to this (where owner and groups should have read/write and execute permissions):

```
total 4
drwxrwx--- 1 admin users   46 Nov 30 19:26 .
drwxrwx--- 1 admin users   16 Jul  2 00:25 ..
drwxrwx--- 1 admin users 4040 Dec  1 23:40 GAMES
drwxrwx--- 1 admin users  224 Dec  1 23:05 PKG
drwxrwx--- 1 admin users  232 Nov 30 19:36 PS3ISO
```

Does your Synology NAS have these shares defined as "Windows" shares or something like that? FreeNAS has a feature like that where you can set a dataset as "Windows" dataset which completely disables the Linux file permission system and makes the files readable for everyone, it looks like Synology does a similar thing but instead of making it readable for everyone it denies access to everything.

Can you somewhere configure the type of your shares in the Synology DSM? Can you post the configuration of your folders in DSM?

Also what does `ls -l /volume1/DATA/COMMUN/JEUX/PS3` output if you change the ownership of your folders directly via `chmod -R 0755 /volume1/DATA/COMMUN/JEUX/PS3` in a terminal?

**Comment by DafreyG** [comment]
Thank You Shawly,

You put me on the right track: admin user had no permission on this Windows shared folder.
I just added RW permission for admin user (Synology DSM interface) and it works perfectly now. 

Thank You very much for your help!

**Comment by shawly** [comment]
No problem, happy new year!
