### ISSUE TITLE
Compatibility report: Raspberry Pi 4 Model B

### ISSUE THREAD

**Issue by vinhtq115** [shawly/docker-ps3netsrv#19]
**Device:**
Raspberry Pi 4 Model B (4GB) (aarch64)

**Distro**
DietPi v7.4.2 (64-bit)

**Status:**
[x] works
[ ] not working

**Additional steps to get it to work?**
- Soft symbolic link not working so I have to change to hard link.

Tested mounting BDISO only. Blu-ray ISO runs fine.

**Comment by shawly** [comment]
Thanks for your report!
