### ISSUE TITLE
segfault when accessing ps3netsrv with multiman

### ISSUE THREAD

**Issue by remlei** [shawly/docker-ps3netsrv#21]
cant access ps3netsrv on multiman, it works with webman-mod though. Im using multiman to dump my disc and transfer it directly to my NAS which running this image.

here's the log

`[Wed Sep 22 09:53:42 2021] ps3netsrv[26267]: segfault at 1 ip 00007f5b5df76540 sp 00007f5b5da0e638 error 4 in ld-musl-x86_64.so.1[7f5b5df3d000+47000]
[Wed Sep 22 09:53:42 2021] Code: ff fe fe fe fe fe fe fe 49 bb 80 80 80 80 80 80 80 80 4c 0f af c0 eb ae 5b c3 40 0f b6 f6 48 89 f8 a8 07 74 14 48 85 d2 74 7c <0f> b6 08 39 f1 74 3f 48 ff c0 48 ff ca eb e8 48 85 d2 74 68 0f b6
`

my finding is multiman was able to connect to ps3netsrv? and when i go to file manager, the directory is empty. I tried creating a new directory inside net0 directly on multiman's filemanager on it and nothing happens, I checked my NAS and see if it created the directory and yes it was indeed, its just that multiman refuse to display the content on my ps3netsrv, and given that error dmesg error showing up everytime I do something on multiman (eg scanning and creating directory).

im running the latest tag on the docker's hub repository x86-64. using it with HEN, it also have the same issue with CFW as well. Using latest webman-mod as well.

**Comment by shawly** [comment]
Can you reproduce this issue with the standalone version of ps3netsrv as well?

**Comment by remlei** [comment]
Nope, only happens in container, if i run the ps3netsrv linux binary
directly, it works just fine.

**Comment by shawly** [comment]
I've looked around and found that there have been some issues with musl and Alpine linux in the past that cause segmentation faults.
I'll update the image to alpine 3.14 with the latest musl package to see if that might fix the issue.

The image will be up in a few minutes, you could update to the `shawly/ps3netsrv:edge` tag then to see if the issue still persists there. If it still doesn't work I might add an image based on debian slim.

**Comment by remlei** [comment]
tried the edge release, and yes the issue is now resolved. thanks!!

**Comment by shawly** [comment]
Alright in that case I'll push a release as well :)
