### ISSUE TITLE
Compatibility report: OrangePi 3 LTS

### ISSUE THREAD

**Issue by Kamillux** [shawly/docker-ps3netsrv#25]
**Device:**
OrangePi 3 LTS
arm64

**Status:**
[] works
[x] not working

**Additional steps to get it to work?**
- none

Webman Mod on PS3 discovers iso images but fails to load. No error logs from "docker logs".

Docker ps3netsrv image 1.6.0
Webman MOD 1.47.42

**Comment by shawly** [comment]
Are you sure this is related to the Docker image? Have you tested it with the standalone version?
