### ISSUE TITLE
Does not work on Synology DS218+

### ISSUE THREAD

**Issue by turbozapekanka** [shawly/docker-ps3netsrv#9]
Not sure what is the issue, but mccloud/ps3netsrv version works (which is 6 months old)
I'm willing to troubleshoot but not sure how.

**Comment by turbozapekanka** [comment]
This error is from the ramdockerapp/ps3netsrv fork :
`/startapp.sh: 4: cd: can't cd to /games`

**Comment by shawly** [comment]
> Not sure what is the issue, but mccloud/ps3netsrv version works

I'd refrain from using mccloud's version, according to users in the UnRAID forum his account has been compromised and someone added mining software into his Docker images. (https://forums.unraid.net/topic/36183-docker-ps3netsrv/)

> This error is from the ramdockerapp/ps3netsrv fork :
> `/startapp.sh: 4: cd: can't cd to /games`

This sounds like a permission issue, make sure you apply the correct permissions to either the container or your shared folder.

After the container starts, you can execute `docker exec -it <your_ps3netsrv_container_name> /bin/sh` and then execute `ls -l /games` and post the result here.
